import { Component, input, output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CurrencyPipe } from '@angular/common';
import { ConfiguracoesLocal } from '../models/configuracoes.model';
@Component({ selector: 'app-capacidade-financeira', imports: [FormsModule, CurrencyPipe], template: `
  <div class="cfg-pilha"><section class="cfg-card cfg-pilha"><div><h3>Capacidade produtiva</h3><p>Quantas horas o escritório realmente consegue faturar por mês. É o denominador da conta: quanto menos horas, mais cara a hora.</p></div>
    <div class="cfg-grade"><button [class.selecionado]="financeiro().modoHoras === 'direto'" (click)="financeiro().modoHoras = 'direto'"><h4>Informar direto</h4><p>Você já sabe quantas horas faturáveis tem no mês.</p></button><button [class.selecionado]="financeiro().modoHoras === 'estrutura'" (click)="financeiro().modoHoras = 'estrutura'"><h4>Calcular pela estrutura</h4><p>A partir do time, da jornada e do percentual produtivo.</p></button></div>
    @if (financeiro().modoHoras === 'estrutura') { <div class="cfg-grade quatro"><label>Advogados<input type="number" min="1" max="10000" [(ngModel)]="financeiro().advogados" /></label><label>Horas por semana<input type="number" min="1" max="168" step="0.01" [(ngModel)]="financeiro().horasSemanais" /></label><label>% produtivas<input type="number" min="1" max="100" step="0.01" [(ngModel)]="financeiro().percentualProdutivo" /><p>O resto é gestão, prospecção, café.</p></label><label>Semanas por mês<input type="number" min="1" max="5" step="0.1" [(ngModel)]="financeiro().semanasPorMes" /><p>4,2 é conservador de propósito.</p></label></div><p>{{ financeiro().advogados }} × {{ financeiro().horasSemanais }} h × {{ financeiro().percentualProdutivo }}% × {{ financeiro().semanasPorMes }} semanas = <strong>{{ horas }} h por mês</strong></p> }
    @else { <label style="max-width:200px">Horas produtivas por mês<input type="number" min="1" max="1000000" step="0.01" [(ngModel)]="financeiro().horas" /></label> }
  </section><section class="cfg-card cfg-pilha"><div><h3>Margem e posicionamento</h3><p>A margem cobre o imprevisto e o crescimento. O fator é o que separa cobrir o custo de construir escritório.</p></div><div class="cfg-grade"><label>Margem de lucro<input type="number" min="0" max="100" [(ngModel)]="financeiro().margemLucro" /><p>Multiplicativa: hora × (1 + margem). 30% aqui dão 23% sobre o preço final.</p></label><label>Fator de posicionamento padrão · {{ financeiro().fatorPosicionamento }}×<input type="range" min="1.5" max="10" step="0.1" [(ngModel)]="financeiro().fatorPosicionamento" /></label></div><div class="cfg-linha cfg-separador"><p class="cresce">Estes números alimentam a Calculadora de Honorários. Gravar aqui vale para todo o escritório.</p><button class="cfg-primario" (click)="salvar.emit()">Salvar capacidade e margem</button></div></section>
    <div class="cfg-grade quatro">@for (indicador of indicadores; track indicador.nome) { <section class="cfg-card"><p>{{ indicador.nome }}</p><h3 style="margin-top:8px">@if (indicador.nome === 'Horas produtivas / mês') { {{ indicador.valor }} h } @else { {{ indicador.valor | currency:'BRL':'symbol':'1.2-2':'pt-BR' }} }</h3><p>{{ indicador.dica }}</p></section> }</div>
  </div>
`, styles: `:host { display:block; } button { text-align:left; } button.selecionado { border-color:var(--tema-primaria); background:var(--tema-suave); } .quatro { grid-template-columns:repeat(4,minmax(0,1fr)); } @media(max-width:800px) { .quatro { grid-template-columns:repeat(2,minmax(0,1fr)); } } @media(max-width:500px) { .quatro { grid-template-columns:1fr; } }` })
export class CapacidadeFinanceira {
  readonly financeiro = input.required<ConfiguracoesLocal['financeiro']>(); readonly total = input(0); readonly salvar = output();
  protected get horas() { const f = this.financeiro(); return f.modoHoras === 'direto' ? Number(f.horas || 0) : Math.round(f.advogados * f.horasSemanais * f.percentualProdutivo / 100 * f.semanasPorMes * 100) / 100; }
  protected get indicadores() { const hora = this.horas ? this.total() / this.horas : 0; return [{ nome: 'Custo fixo / mês', valor: this.total(), dica: 'Soma dos custos operacionais' }, { nome: 'Horas produtivas / mês', valor: this.horas, dica: 'Capacidade faturável' }, { nome: 'Hora técnica mínima', valor: hora, dica: 'Ponto de equilíbrio' }, { nome: 'Hora técnica recomendada', valor: hora * (1 + this.financeiro().margemLucro / 100), dica: 'Com a margem de lucro' }]; }
}

